# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: Ryan Donaldson's Blog
description: > # this means to ignore newlines until "email:"
   A blog to write to your mother about

email: ryjdon@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Ryan Donaldson'
author: 'Ryan Donaldson'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://ryjdon.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/watersandwich
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	fa-instagram 
    url:	https://instagram.com/watersandwich  
    desc: Follow me on Instagram
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/ryjdon
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
